[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api-proxy/*"
  to = "https://mg.aid.pub/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
